PREFIX oml: 			<http://opencaesar.io/oml#>
PREFIX base:        <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX mission:        <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX sa: 	<http://example.com/tutorial2/vocabulary/stateanalysis#>
PREFIX analysis: <http://imce.jpl.nasa.gov/foundation/analysis#>


SELECT DISTINCT ?scenario ?iri ?scenario_instancename ?statevariable ?value ?type
WHERE {

  VALUES ?componentType {sa:simulationScenario}

	?scenario a ?componentType .
  
	?scenario analysis:asserts ?analysisTarget.
    OPTIONAL{
        ?analysisTarget sa:isAffectedBy* ?iri .
        OPTIONAL{
	         ?r oml:hasTarget ?iri.
      			OPTIONAL{
              ?r sa:assumeInitialStateValue ?value. 
  #           BIND("DesignVariables" as ?type).
          	}
    	}    
 	 }
  BIND( IF(?iri = ?analysisTarget, "OBJECTIVE", IF( BOUND(?value),"DesignVariables","Dependents")) AS ?type). 


  
   #	Recursive Query to get state variables

  	  
#    BIND(STRAFTER(STR(?scenario ), "#") AS ?scenario_instancename ) .

  BIND(STRAFTER(STR(?scenario), "#") AS ?scenario_instancename) .
  BIND(STRAFTER(STR(?iri), "#") AS ?statevariable) .
 }
ORDER BY ?c1_id